changelog:
  exclude:
    labels:
      - dependencies
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 💡
      labels:
        - enhancement
    - title: Bug Fixes 🧰
      labels:
        - bug
    - title: Deprecations 🚩
      labels:
        - deprecation
    - title: Other Changes ⚡
      labels:
        - "*"