name: Create Labels
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-labels:
    strategy:
        matrix:
          labels: [breaking change, sub-issue, deprecated]
          include:
            - label: breaking change
              color: 0A4139
              desc: "Changes that are not backwards compatitable"
            - label: sub-issue
              color: 57DE6C
              desc: "Broken down issue"
            - label: deprecated
              color: 45B683
              desc: "A component that is deprecated"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - name: Create Github Release 📁
        run: |
          gh label create -f ${{ matrix.label }} -d "${{ matrix.desc }}" -c ${{ matrix.color }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          RELEASE_TAG: ${{ steps.github_tag.outputs.tag }}