name: Create issue
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-labels:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      issues: ${{ steps.create-issue.outputs.issue }}
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - name: Create Github issue 🔖
        id: create-issue
        run: |
          echo issue=$( gh issue create --title 'Align with template repo' --body 'Update with changes from latest release in template repo' --label 'enhancement' --repo https://github.com/$OWNER/$REPO ) >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - run: |
          sed -i -E '/Tasks/Tasks\\n\-  "${{ steps.create-issue.outputs.issue }}" /g' .github/workflows/templates/issue.md

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./.github/templates/issue.md
  print-output:
    runs-on: ubuntu-latest
    permissions: write-all
    needs:
      - create-labels
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - name: Create Github issue 🔖
        run: |
          echo "${{needs.create-labels.outputs.issues}}"