name: Create issue
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: issue-body
          path: .github/workflows/templates/issue.md
  create-labels:
    needs: [ create-artifact ]
    strategy:
        matrix:
          repo: [panys9/config_baseline, panys9/automatic_releases]
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      issues: ${{ steps.create-issue.outputs.issue }}
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: issue-body
      - name: Create Github issue 🔖
        id: create-issue
        run: |
          echo issue=$( gh issue create --title 'Align with template repo' --body 'Update with changes from latest release in template repo' --label 'enhancement' --repo https://github.com/${{ matrix.repo }} ) >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
      - name: Add new content to file
        run: |
          sed -i 's|Tasks|Tasks\n\- \[ \] ${{ steps.create-issue.outputs.issue }}|g' .github/workflows/templates/issue.md
      - name: Update artifact
        uses: actions/upload-artifact@v3
        with:
          name: issue-body
          path: .github/workflows/templates/issue.md
  print-output:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [ create-labels ]
    steps:
      - name: Checkout Repo ✅
        uses: actions/checkout@v3
      - name: Create Github issue 🔖
        run: |
          echo "${{needs.create-labels.outputs.issues}}"